project:
  type: website

website:
  title: Quarto demo
  navbar:
    left:
      - href: index.qmd
        text: R
      - href: python.qmd
        text: Python
      - href: observable.qmd
        text: Plotly/ObservableJS
      - href: shinylive.qmd
        text: ShinyLive

format:
  html:
    theme: cosmo
    toc: true

execute:
  freeze: auto
